# Generated by Django 2.0 on 2019-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0002_auto_20190603_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='dept',
            field=models.CharField(choices=[('信息', '信息工程学院'), ('理', '理学院'), ('软件', '软件学院'), ('体育', '体育学院'), ('艺术', '艺术学院'), ('外国语', '外国语学院')], default='信息', max_length=20, verbose_name='学院'),
        ),
    ]
