# Generated by Django 2.0 on 2019-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0003_auto_20190603_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='name',
            field=models.CharField(choices=[('w1', '物联网工程1班'), ('w2', '物联网工程2班'), ('j1', '计算机1班'), ('j2', '计算机2班'), ('t0', '通信工程卓越班'), ('t1', '通信工程1班'), ('t2', '通信工程2班')], default='w1', max_length=20, unique=True, verbose_name='班级名称'),
        ),
    ]
