# Generated by Django 2.0 on 2019-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0004_auto_20190603_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='grade',
            field=models.CharField(choices=[('18', '2018级'), ('17', '2017级'), ('16', '2016级'), ('15', '2015级')], default='16', max_length=20, verbose_name='年级'),
        ),
    ]
