# Generated by Django 2.0 on 2019-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0006_auto_20190603_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='scoreship',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='student',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
    ]
