# Generated by Django 2.0 on 2019-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0007_auto_20190603_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='score',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'teacher_name')},
        ),
    ]
