# Generated by Django 2.0 on 2019-06-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0008_auto_20190603_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='score',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
