# Generated by Django 2.0 on 2019-06-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0009_auto_20190603_1800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoreship',
            unique_together={('course', 'student', 'term')},
        ),
    ]
