# Generated by Django 2.0 on 2019-06-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0011_auto_20190603_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'teacher_name'), ('name',)},
        ),
    ]
