# Generated by Django 2.0 on 2019-06-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0012_auto_20190603_1954'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
