# Generated by Django 2.0 on 2019-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0014_auto_20190603_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreship',
            name='daily_score',
            field=models.FloatField(verbose_name='平时成绩'),
        ),
        migrations.AlterField(
            model_name='scoreship',
            name='exam_score',
            field=models.FloatField(verbose_name='考试成绩'),
        ),
    ]
