# Generated by Django 2.0 on 2019-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0015_auto_20190603_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreship',
            name='sum_score',
            field=models.FloatField(default=models.FloatField(verbose_name='考试成绩'), verbose_name='test'),
        ),
    ]
