# Generated by Django 2.0 on 2019-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0015_auto_20190603_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreship',
            name='sum_score',
            field=models.FloatField(default=0, verbose_name='单科成绩总评分'),
        ),
    ]
