# Generated by Django 2.0 on 2019-06-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0016_scoreship_sum_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreship',
            name='sum_score',
        ),
    ]
