# Generated by Django 2.0 on 2019-06-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0018_auto_20190610_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='dept',
            field=models.CharField(choices=[('信息', '信息工程学院')], max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='grade',
            field=models.CharField(choices=[('18', '2018级'), ('17', '2017级'), ('16', '2016级'), ('15', '2015级')], max_length=20, verbose_name='年级'),
        ),
    ]
