# Generated by Django 2.0 on 2019-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', '管理员'), ('regular', '普通用户'), ('anon', '匿名用户')], default='regular', max_length=20, verbose_name='用户类型'),
        ),
    ]
