# Generated by Django 2.0 on 2019-06-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acheve_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('admin', '管理员'), ('regular', '普通学生')], default='admin', max_length=20, verbose_name='学生类型'),
        ),
    ]
